### ISSUE TITLE
A small question & a big Thank you! :-D

### ISSUE THREAD

**Issue by mm108** [ToniKorin/cordova-plugin-autostart#1]
Not really issues with the plugin as such. Mainly wanted to thank you for the plugin that is quite useful to me. It seems to be working reliably on couple of devices that I tested it with. However I have a small doubt regarding the code below, used in the AndroidManifest file

```
            <receiver
                android:name="com.tonikorin.cordova.plugin.autostart.PackageReplacedReceiver" android:enabled="true">>
                <intent-filter>
                    <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
                </intent-filter>
            </receiver>
```

Even though the plugin works I was curious - do I need to replace the MY_PACKAGE_REPLACED with my bundle id / package name or something?

And again thanks a ton for the plugin. 

Cheers,
M&M

**Comment by ToniKorin** [comment]
Glad to hear that you found it useful :). No need to replace anything, at least it was my intention. Ref:
http://developer.android.com/reference/android/content/Intent.html#ACTION_MY_PACKAGE_REPLACED

**Comment by mm108** [comment]
cool, thank you :)

Cheers,
M&M
