### ISSUE TITLE
runs at startup but runs in its full glory

### ISSUE THREAD

**Issue by halukkaramete** [ToniKorin/cordova-plugin-autostart#10]
Hi Toni,

I installed your plugin on ionic and it does work and work as expectedly. However, I think there is one side-effect that the end users may not like. 

When the phone reboots, users are greeted with my app ( as soon as they pass the lock screen ). That's because your plug in kicks in and starts running my app. The problem is now the user has to do something ( such as pressing on the home button ) si that they can see their normal home/desktop view. And this is something they have to go thru, every single time, the phone is shutdown and reboots. 

Is there a way to modify the plug in so that the associated app starts running in the background at startup, rather than running it in the foreground like this?

**Comment by ToniKorin** [comment]
Hi,

It might be possible. Anyway a cordova app needs to be in active state (visible) at least once. After that your app could use functions of "de.appplant.cordova.plugin.background-mode" and "cordova-plugin-backbutton" plugins to automatically move your app to the background.

But in addition it is needed  a status about if the start-up is initiated by this plugin or user (see https://github.com/ToniKorin/cordova-plugin-autostart/issues/7). If you have time feel free to improve this plugin.

**Comment by halukkaramete** [comment]
why the need for "cordova-plugin-backbutton"? I can see the need for the "de.appplant.cordova.plugin.background-mode" presence but don't get the point on the "cordova-plugin-backbutton". could you eloborate?

**Comment by ToniKorin** [comment]
It hides your app and brings the home view in front (navigator.Backbutton.goHome). The "background-mode" plugin requires user actions for it.

**Comment by halukkaramete** [comment]
got you... does that mean we will end up with no ios support? 

cause as you know, ios does not have a dedicated-and-always available-backbutton functionality. ( it sure has some back/forward in some apps ( such as in safari but most apps do not have a motion of back). 

In contrast, on an android environment, say, from a desktop/home view, i can open gmail for instance,and then press the backbutton, and this would send the gmail to background while placing me back on the desktop/home view. I cannot do this on ios.

**Comment by ToniKorin** [comment]
The backbutton is not the reason. The iOS itself limits and controls background tasks much more than  Android. E.g. the iOS implementation of "de.appplant.cordova.plugin.background-mode" prevents the acceptance of Apple appstore.  Your app needs to be a native VoIP app to get a full background support with the automatic start-up. See more details at
http://stackoverflow.com/questions/9300815/can-iphone-apps-start-on-start-up

**Comment by ZengYJ** [comment]
Hi.I am using the plugin and it does't works when the phone reboot.I want to auto start the app in background and do something such as connecting the bluetooth when the phone reboot. Would give me some help .Thanks a lot.

**Comment by ToniKorin** [comment]
So your app won't start at all?
Maybe because of the installation to the SD card will prevent it?

**Comment by ZengYJ** [comment]
Yes. the app does't start at all. How can i know where the app is installed ? I only used 'ionic run android ' to install the app to the phone.

**Comment by dzigns** [comment]
I am interested in auto launching my app at boot. However I cannot seem to get this plugin to work with my Ionic app. Can you give me specifics on how you installed the plugin & what you added to the config.html file or the app.js file to get this to work?

**Comment by ToniKorin** [comment]
Have you checked the android logs?

**Comment by ToniKorin** [comment]
The requested enhancement "run at startup in to the background" added to the TODO list...

**Comment by ricardoricky92** [comment]
Is there any way to make the application always running, ignoring the buttons of: Home, Back, Recentapps? that is, block those buttons so that the app is always running?
