### ISSUE TITLE
Long time until start

### ISSUE THREAD

**Issue by andersborgabiro** [ToniKorin/cordova-plugin-autostart#14]
Maybe a feature more than a bug: It takes 40 seconds after the device is ready before the app is started. Can this be controlled?

Cheers,
Anders

**Comment by ToniKorin** [comment]
The starting is triggered by android events "BOOT_COMPLETED" (or "USER_PRESENT" if the device is locked after the boot) and then your app is immediately launched. I think it is not possible to speed it up.

**Comment by andersborgabiro** [comment]
OK. At least it's an explanation :).

Thanks,
Anders

**Comment by FrancescoMussi** [comment]
Also for me it is very slow.
On a Samsung J5 with Android 7.1.1. it takes around 2'22''
On a Samsung Tablet wiht Android 7.0 it takes around 40'

Still no way to speed it up?
Maybe it depends by the number of apps installed?
