### ISSUE TITLE
Not working on Android 5.0.1

### ISSUE THREAD

**Issue by kamleshpra995** [ToniKorin/cordova-plugin-autostart#19]
I implemented this in my app. 

Working with Andoird 7 but not with 5.0.1.

please help.

**Comment by miguelavaqrod** [comment]
Hi,

Same here.. any news?

Thanks in advance

**Comment by miguelavaqrod** [comment]
Sorry, I found myself the solution and it was an Android app blocking autostart functionality.
Thanks!
