### ISSUE TITLE
&gt; symbol at end of receiver

### ISSUE THREAD

**Issue by mountainrock** [ToniKorin/cordova-plugin-autostart#2]
<receiver
                android:name="com.tonikorin.cordova.plugin.autostart.BootCompletedReceiver" android:enabled="false">>

There is a greater than symbol at end of receiver (all three receiver tags have it). Please remove it.

Nice work. Thanks much.

**Comment by ToniKorin** [comment]
Done for git. Have you faced any problems with this typo? If not I won't release a new version to cordova.io.

**Comment by mountainrock** [comment]
Yes,  while building the APK using cordova 5.0 it would say duplicate receiver found. I think it was trying to merge the receiver on every build because of this typo.

**Comment by ToniKorin** [comment]
Ok,  thanks for the info. Now the fix is also published to plugins.cordova.io in the version 1.2.1.
