### ISSUE TITLE
This is not working with android MI 4i

### ISSUE THREAD

**Issue by chiragkheni78** [ToniKorin/cordova-plugin-autostart#3]
Android MI 4i have its own security app and its contained our application disable by default for autostart, so we need to enable it manually. So any solutions for that ?

**Comment by ToniKorin** [comment]
I'm afraid that it is impossible to override the security app. So the only solution would be to instruct end-users to allow the auto-start manually.

**Comment by sanjib-dev** [comment]
Am using the Redmi note 4. 
My app has been disabled by the security app for autostart but some app which i have installed have the permission to start in background (auto-start).
Any idea on how to achieve this? 
My Android version is 7.1.
