### ISSUE TITLE
This plugin is working for 2 times only after the app istallation . I am working in intel xdk  version 2366to develop mobile apps with cordova 4.1.2 .Please help me to rectify this problem .Thank You

### ISSUE THREAD

**Issue by bhavya007** [ToniKorin/cordova-plugin-autostart#4]

**Comment by ToniKorin** [comment]
So do you mean that after the 3. reboot your app won't start at all OR your app is pushed to the front two times in row? Have you checked the android logs about exceptions?

**Comment by bhavya007** [comment]
After 2 nd reboot the app won't start at all i have to forcefully start my app with the click . Please help me with it .
Thank You

**Comment by ToniKorin** [comment]
And any hints from the android logs? You could also comment in some debug logs of the autostart plugin.

**Comment by bhavya007** [comment]
Which build will you prefer ?
a) Cordova hybrid android OR
b) Cordova hybrid Crosswalk-android

**Comment by ToniKorin** [comment]
I'm not familiar with those builds. Anyway I guess it does not matter. So have you pre-analyzed the logs yourself?

**Comment by bhavya007** [comment]
Sir,
Thank you so much for your support . Sir i got the the solution the issue was that i was installing  the application in my sd card instead of my device  memory . Now your plugin is working effectively thank you once again for giving me time and  your support .

**Comment by ToniKorin** [comment]
Good to know that the installation into SD card has a such effect.
