### ISSUE TITLE
Using with Stencil + Cordova

### ISSUE THREAD

**Issue by daniell0gda** [ToniKorin/cordova-plugin-autostart#42]
I don't have ionic project installed, could you please tell me what should I do to sync this plugin to android project?
![image](https://user-images.githubusercontent.com/8320732/103478664-8d0a6a00-4dc8-11eb-91a4-f688dd5310f6.png)

`npx cap update ` cannot find it.

I think it is not compatible because it ins't exposed to capacitor [correctly](https://capacitorjs.com/docs/plugins/android#export-to-capacitor) or I am wrong?

Important package versions

    "@capacitor-community/electron": "^1.3.2",

    "@capacitor-community/keep-awake": "^1.0.0",

    "@capacitor/android": "^3.0.0-alpha.11",

    "@capacitor/app": "^0.1.2",

    "@capacitor/cli": "^3.0.0-alpha.11",

    "@capacitor/core": "^3.0.0-alpha.9",

    "@capacitor/toast": "^0.2.2",

    "@ionic-native/autostart": "^5.30.0",

    "@ionic/core": "^5.5.2",

    "cordova-plugin-autostart": "^2.3.0",`

**Comment by Maxime145** [comment]
Hello, you are using an alpha version of capacitor.
Did you attempt to revert to a stable version ? (Or update @capacitor/core to alpha.11) ?

Other than that I don't see where the problem can come from :(

**Comment by daniell0gda** [comment]
Damnit, you are right. I've tried on side project downgrade it and it then found it.
I guess then it is capacitor bug? and I should close this issue?

**Comment by Maxime145** [comment]
I think yes you can close this issue.
