### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by alaanasreng** [ToniKorin/cordova-plugin-autostart#6]
i installed the plugin and add this code to my js:
cordova.plugins.autoStart.enable();
and after installing the app and reboot the device the app not started automatically

any help please? @ToniKorin

**Comment by ToniKorin** [comment]
Have you checked the android logs?
During the boot phase the network connectivity is available after the pin unlock. So if your app is loading something over the network during the start up, it may cause your app to crash.

**Comment by alaanasreng** [comment]
how to check android logs?
i dont have any pin lock. @ToniKorin

**Comment by ToniKorin** [comment]
Here you go:
http://developer.android.com/tools/help/monitor.html

**Comment by alaanasreng** [comment]
hello sir,
i checked android logs, and don't have any messages for the app at booting device.
so the app doesn't start
any help please? @ToniKorin

**Comment by antiPoP** [comment]
Similar issue here. The plugin does not start the app at boot, but works fine when updating the app with `adb install -r`. Is required some specific android version or permission to make it work?

**Comment by ToniKorin** [comment]
I just re-verified android versions 4, 5 and 6 successfully. I don't see any obstacles about older versions either. The plugin itself enables the required permission for RECEIVE_BOOT_COMPLETED. Do you have any special configuration, which could lead to this unwanted result?

**Comment by antiPoP** [comment]
I just made a trivial "Hello World" app with only this plugin and I got the same results. I'm using the latest Cordova version (5.4.0).

**Comment by alaanasreng** [comment]
hello sir,
i don't have any special configuration, and i test app on "Galaxy Tab 4.0"

**Comment by ToniKorin** [comment]
Btw, it was also discovered that the installation into SD card prevents the start after the boot for some reason.

**Comment by antiPoP** [comment]
Installing in internal storage (`adb` and without the `-s` switch) works as expected. Is possible to fix the plugin so it also works with the sdcard?

**Comment by ToniKorin** [comment]
Unfortunately it seems to be impossible:
http://stackoverflow.com/questions/9556944/broadcastreceiver-not-working-when-app-is-installed-on-sd-card 

To avoid unnecessary hassle in the future I just updated the Readme about the limitations... ;)
