### ISSUE TITLE
Detect when the app is started at boot

### ISSUE THREAD

**Issue by antiPoP** [ToniKorin/cordova-plugin-autostart#7]
Would be possible to detect when the app has been started by the plugin and when by the user? By that way specific actions could be made depending on the scenario?

Thanks.

**Comment by ToniKorin** [comment]
Yes, it could be possible. Maybe it would be easier to use the SharedPreferences than the content of the Intent. Right now I am quite busy with other tasks, so feel free to contribute to this plugin yourself. :)

**Comment by antiPoP** [comment]
Thanks, I haven't worked with Java/Android code yet, but I could give it a try.

**Comment by antiPoP** [comment]
Another possible feature could be checking if the plugin is enabled or not (maybe this is easier).

**Comment by ToniKorin** [comment]
Also feasible. :)

**Comment by henryemekaofozor** [comment]
Hi can the plugin be configured to startup an app based on user location ?

**Comment by ToniKorin** [comment]
Nope.

**Comment by henryemekaofozor** [comment]
Hi Toni,

I need to contact you  to develop a custom plugin.  send me a mail on henryofozor@[gmail][.com]

**Comment by ToniKorin** [comment]
The "Detect when the app is started at boot" feature added to TODO list...

**Comment by paredesivan** [comment]
@lentschi how can i detect whe the app is run by the user or by the plugin?

**Comment by lentschi** [comment]
@paredesivan See the [explanation at the pull request](https://github.com/ToniKorin/cordova-plugin-autostart/pull/16). ;-)
Tell me, if this works for you!
