### ISSUE TITLE
Plugin not Installed using Visual Studio 2015

### ISSUE THREAD

**Issue by sathishkumartriyam** [ToniKorin/cordova-plugin-autostart#8]
Hi sir,
i am using visual studio 2015 and creating sample cordova application and i try to add your plugin via visual studio it shows "visual studio was unable to parse plugin.xml".
![err](https://cloud.githubusercontent.com/assets/16348373/11893602/e8cb0cca-a597-11e5-8e83-23e6f3845ee5.png)

any one help?

**Comment by ToniKorin** [comment]
Hi, And what the full installation log says?

**Comment by sathishkumartriyam** [comment]
Hi sir,
the full log says "Visual Studio was unable to parse plugin.xml. please ensure plugin.xml exists and contains no errors."

**Comment by ToniKorin** [comment]
Please could you try open the plugin.xml into VS2015. Does VS indicate some
errors then?

2015-12-18 11:47 GMT+02:00 SathishkumarNew notifications@github.com:

**Comment by sathishkumartriyam** [comment]
yes sir when i open plugin.xml using VS2015 its shows some errors on following tags
<receiver
                android:name="com.tonikorin.cordova.plugin.autostart.BootCompletedReceiver" android:enabled="false">
                <intent-filter>
                    <action android:name="android.intent.action.BOOT_COMPLETED" />
                </intent-filter>
            </receiver>

**Comment by sathishkumartriyam** [comment]
![err2](https://cloud.githubusercontent.com/assets/16348373/11894176/886c9e76-a59b-11e5-8501-60f6d0ac4494.png)

**Comment by ToniKorin** [comment]
It seems to be a common VS2015 problem:
http://stackoverflow.com/questions/33727982/visual-studio-2015-add-plugin-unable-to-parse-plugin-xml-android-namespaces

Please could you contact VS2015 support?

**Comment by sathishkumartriyam** [comment]
ok sir. thanks for your reply
